package com.speedwatch.app.domain

import com.speedwatch.app.data.model.IspSettings
import com.speedwatch.app.data.model.SpeedLog
import java.text.SimpleDateFormat
import java.util.*

class ReportGenerator {

    fun generateMonthlyReport(
        ispSettings: IspSettings?,
        logs: List<SpeedLog>,
        month: Int,
        year: Int,
        isPremium: Boolean = false
    ): String {
        val calendar = Calendar.getInstance()
        val monthLogs = logs.filter { log ->
            calendar.timeInMillis = log.timestamp
            calendar.get(Calendar.MONTH) == month && calendar.get(Calendar.YEAR) == year
        }

        if (monthLogs.isEmpty()) return "No data available for the selected month."

        val avgDownload = monthLogs.map { it.downloadSpeedMbps }.average()
        val avgUpload = monthLogs.map { it.uploadSpeedMbps }.average()
        val avgLatency = monthLogs.map { it.latencyMs }.average()
        val maxDownload = monthLogs.maxOf { it.downloadSpeedMbps }
        val minDownload = monthLogs.minOf { it.downloadSpeedMbps }

        val sdf = SimpleDateFormat("MMMM yyyy", Locale.getDefault())
        val monthName = sdf.format(calendar.apply { 
            set(Calendar.MONTH, month)
            set(Calendar.YEAR, year)
        }.time)

        val report = StringBuilder()
        report.append("SpeedWatch Network Performance Report\n")
        report.append("Period: $monthName\n")
        if (isPremium) report.append("PRO VERSION REPORT\n")
        report.append("----------------------------------\n\n")

        if (ispSettings != null) {
            report.append("ISP: ${ispSettings.ispName}\n")
            report.append("Plan Speed: ${ispSettings.promisedDownloadMbps} Mbps\n")
            report.append("Target Download: ${ispSettings.promisedDownloadMbps} Mbps\n")
            report.append("Target Upload: ${ispSettings.promisedUploadMbps} Mbps\n\n")
            
            val belowPromiseCount = monthLogs.count { it.downloadSpeedMbps < ispSettings.promisedDownloadMbps * 0.9 }
            val compliancePercent = ((monthLogs.size - belowPromiseCount).toDouble() / monthLogs.size) * 100
            report.append("SLA Compliance (90%% Threshold): %.1f%%\n".format(compliancePercent))
            report.append("Tests below threshold: $belowPromiseCount out of ${monthLogs.size}\n\n")
            
            if (isPremium) {
                val critLimit = ispSettings.promisedDownloadMbps * 0.5
                val criticalFailures = monthLogs.count { it.downloadSpeedMbps < critLimit }
                report.append("Critical Performance Dips (<50%%): $criticalFailures\n")
                
                val eveningLogs = monthLogs.filter { 
                    calendar.timeInMillis = it.timestamp
                    calendar.get(Calendar.HOUR_OF_DAY) in 18..23
                }
                if (eveningLogs.isNotEmpty()) {
                    val eveningAvg = eveningLogs.map { it.downloadSpeedMbps }.average()
                    report.append("Peak Hours Average (6PM-11PM): %.1f Mbps\n".format(eveningAvg))
                }
                report.append("\n")
            }
        }

        report.append("Summary Statistics:\n")
        report.append("- Average Download: %.2f Mbps\n".format(avgDownload))
        report.append("- Average Upload: %.2f Mbps\n".format(avgUpload))
        report.append("- Average Ping: %.0f ms\n".format(avgLatency))
        report.append("- Peak Download: %.2f Mbps\n".format(maxDownload))
        report.append("- Minimum Download: %.2f Mbps\n".format(minDownload))
        report.append("\nTotal Tests Recorded: ${monthLogs.size}\n")
        report.append("\nGenerated by SpeedWatch App")

        return report.toString()
    }
}
